### PR TITLE
Ignoring/Filtering features

### PR DESCRIPTION
**Pull request by SocksTheWolf**
This change makes it such that users can easily filter out users/command messages from chat, thus getting rid of a lot of noise that could show up in the SDV chat window

### CODE REVIEW

**Comment by SocksTheWolf** [comment]
[TwitchChatIntegration 1.1.1.zip](https://github.com/user-attachments/files/15942224/TwitchChatIntegration.1.1.1.zip)

Here's the binary build as well.

**Comment by SocksTheWolf** [comment]
New configs look like this:

`  "IgnoredAccounts": [
    "user1",
    "user2"
  ],
  "IgnoreCommands": true`

**Comment by SocksTheWolf** [comment]
[TwitchChatIntegration 1.2.1.zip](https://github.com/user-attachments/files/15943776/TwitchChatIntegration.1.2.1.zip)

Here's the build for Nexus as well.

**Comment by Enteligenz** [comment]
Nice, looks great! Thanks again!
(Also, at this point I feel like you've given this mod more love than me, so if you ever feel like you want to take it over, just tell me :') )

**Pull request merged**
